-- MySQL Script generated by MySQL Workbench
-- Tue Dec  6 09:46:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema exo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `exo` ;


CREATE SCHEMA IF NOT EXISTS `exo` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema exo
-- -----------------------------------------------------
USE `exo` ;

-- -----------------------------------------------------
-- Table `exo`.`Coucou_Livres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exo`.`Coucou_Livres` ;

CREATE TABLE IF NOT EXISTS `exo`.`Coucou_Livres` (
  `id_livre` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(100) NULL,
  `isbn_10` BIGINT NULL,
  `auteur` VARCHAR(100) NULL,
  `prix` FLOAT NULL,
  PRIMARY KEY (`id_livre`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

SELECT * FROM exo.Coucou_Livres;
INSERT INTO Coucou_Livres (titre,isbn_10,auteur,prix) 
VALUES ('Forteresse digitale', '2709626306', 'Dan Brown', '20.5' ),
('La jeune fille et la nuit', '2253237620', 'Guillaume Musso', '21.9'),
('T\'choupi se brosse les dents', '2092589547', 'Thierry Courtin', '5.7'),
( 'La Dernière Chasse', '2226439412', 'Jean-Christophe Grangé', '22.9'),
('Le Signal', '2226319484', 'Maxime Chattam', '23.9');

